[package]
name = "raytracing_weekend_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "=0.28.0"
indicatif = "0.17.8"
